package com.javarush.task.task07.task0712;                                                                                                                                                                                                                                                                                                                                                              
                                                                                                                                                                                                                                                                                                                                                              
import java.io.BufferedReader;                                                                                                                                                                                                                                                                                                                                                              
import java.io.IOException;                                                                                                                                                                                                                                                                                                                                                              
import java.io.InputStreamReader;                                                                                                                                                                                                                                                                                                                                                              
import java.util.ArrayList;                                                                                                                                                                                                                                                                                                                                                              
                                                                                                                                                                                                                                                                                                                                                              
/*                                                                                                                                                                                                                                                                                                                                                               
Самые-самые                                                                                                                                                                                                                                                                                                                                                              
*/                                                                                                                                                                                                                                                                                                                                                              
                                                                                                                                                                                                                                                                                                                                                              
public class Solution {                                                                                                                                                                                                                                                                                                                                                              
    public static void main(String[] args) throws IOException {                                                                                                                                                                                                                                                                                                                                                              
        //напишите тут ваш код                                                                                                                                                                                                                                                                                                                                                              
                                                                                                                                                                                                                                                                                                                                                              
        BufferedReader reader = new BufferedReader(new InputStreamReader(System.in));                                                                                                                                                                                                                                                                                                                                                              
        ArrayList<String> list = new ArrayList<>(10);                                                                                                                                                                                                                                                                                                                                                              
        int moreLong = 0;                                                                                                                                                                                                                                                                                                                                                              
        int moreShort = 0;                                                                                                                                                                                                                                                                                                                                                              
                                                                                                                                                                                                                                                                                                                                                              
        for (int i = 0; i < 10; i++){                                                                                                                                                                                                                                                                                                                                                              
            list.add(reader.readLine());                                                                                                                                                                                                                                                                                                                                                              
            if(i==0){                                                                                                                                                                                                                                                                                                                                                              
                moreLong = list.get(i).length();                                                                                                                                                                                                                                                                                                                                                              
                moreShort = list.get(i).length();                                                                                                                                                                                                                                                                                                                                                              
            }                                                                                                                                                                                                                                                                                                                                                              
            if(i!=0){                                                                                                                                                                                                                                                                                                                                                              
                if(moreLong < list.get(i).length()){                                                                                                                                                                                                                                                                                                                                                              
                    moreLong = list.get(i).length();                                                                                                                                                                                                                                                                                                                                                              
                }                                                                                                                                                                                                                                                                                                                                                              
                if(moreShort > list.get(i).length()){                                                                                                                                                                                                                                                                                                                                                              
                    moreShort = list.get(i).length();                                                                                                                                                                                                                                                                                                                                                              
                }                                                                                                                                                                                                                                                                                                                                                              
            }                                                                                                                                                                                                                                                                                                                                                              
        }                                                                                                                                                                                                                                                                                                                                                              
                                                                                                                                                                                                                                                                                                                                                           
                                                                                                                                                                                                                                                                                                                                                             
            for (String s: list) {                                                                                                                                                                                                                                                                                                                                                              
               if(s.length() == moreLong || s.length() == moreShort){                                                                                                                                                                                                                                                                                                                                                              
                   System.out.println(s);                                                                                                    
                   break;                                                                                                                                                                                                                                                                                                                                                      
               }                                                                                                                                                                                                                                                                                                                                                              
                                                                                                                                                                                                                                                                                                                                                                        
        }                                                                                                                                                                                                                                                                                                                                                              
    }                                                                                                                                                                                                                                                                                                                                                              
}